name: Run Example

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Create output directory
        run: mkdir test/output
      - name: Run python-test-runner on example files
        run: sh run-in-docker.sh example test/ test/output/
      - name: Verify that results.json is created
        run: test -f test/output/results.json && cat test/output/results.json
      - name: Verify that test case order in results.json
        run: bash verify_test_order.sh example test/ test/output
