---
name: CI

on:
  push:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - '**.md'

jobs:
  build:
    name: Test Runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build Docker Image
        run: docker build -f Dockerfile -t python-test-runner .

      - name: Run Tests
        run: docker run --entrypoint "pytest" python-test-runner
